### ISSUE TITLE
LODE todos

### ISSUE THREAD

**Issue by PicoCentauri** [Luthaf/rascaline#106]
We have a working LODE version but still some TODO's to get an even more performing, tested version:

- [x] Add `center_atom_weight` parameter similar as in SOAP. #123
- [x] port high p=1 level pyLODE tests (Madelung constants, Random Coulomb Structures, Super cells) #123
- [x] add regression tests for `compute_k0_contributions`, `compute_density_fourrier`, `project_k_to_nlm`, `compute_structure_factors` #123, #133
- [ ] enable parallelism (likely over systems like for the SOAP spherical expansion)
